#!/bin/bash

echo Killing any existing synergy clients...
killall synergyc

# sh 
#if [ -z "omg" ] -a [ 'd' == "$1" ]; then
#if [  "$1" ]; then if  [ $1 == 'd' ]
if [ "$1" == 'd' ]
	then 
		synergyc --debug DEBUG -f $2
	else
		synergyc $1
	fi
# else	
# 	echo Usage:
# 	echo synergyserver [d]
# 	echo
# 	echo d to get synergys to output DEBUG level messages and not daemonize
# 	echo
# fi
