#!/bin/bash

if [ -n "$1" ]; then
	if [ "$1" == work ]; then
		xrandr --output LVDS --mode 1920x1080 --right-of VGA-0 --output VGA-0 --mode 1920x1080
	elif [ "$1" == home ]; then 
		xrandr --output LVDS --mode 1920x1080 --left-of VGA-0 --output VGA-0 --mode 1440x900 # 1280x1024
	elif [ "$1" == none ]; then
		xrandr --output LVDS --mode 1920x1080 --output VGA-0 --off
	fi
else
	echo
	echo "gkrandr home"
	echo or
	echo "gkrandr work"
	echo or
	echo "gkrandr none"
fi
